### YamlMime:ManagedReference
items:
- uid: Vasont.Inspire.SDK.Configuration
  commentId: N:Vasont.Inspire.SDK.Configuration
  id: Vasont.Inspire.SDK.Configuration
  children:
  - Vasont.Inspire.SDK.Configuration.ConfigurationExtensions
  langs:
  - csharp
  - vb
  name: Vasont.Inspire.SDK.Configuration
  nameWithType: Vasont.Inspire.SDK.Configuration
  fullName: Vasont.Inspire.SDK.Configuration
  type: Namespace
  assemblies:
  - Vasont.Inspire.SDK
references:
- uid: Vasont.Inspire.SDK.Configuration.ConfigurationExtensions
  commentId: T:Vasont.Inspire.SDK.Configuration.ConfigurationExtensions
  parent: Vasont.Inspire.SDK.Configuration
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Vasont.Inspire.SDK.Configuration.ConfigurationExtensions
- uid: Vasont.Inspire.SDK.Configuration
  commentId: N:Vasont.Inspire.SDK.Configuration
  name: Vasont.Inspire.SDK.Configuration
  nameWithType: Vasont.Inspire.SDK.Configuration
  fullName: Vasont.Inspire.SDK.Configuration
