### YamlMime:ManagedReference
items:
- uid: Vasont.Inspire.SDK.Application
  commentId: N:Vasont.Inspire.SDK.Application
  id: Vasont.Inspire.SDK.Application
  children:
  - Vasont.Inspire.SDK.Application.ApplicationExtensions
  langs:
  - csharp
  - vb
  name: Vasont.Inspire.SDK.Application
  nameWithType: Vasont.Inspire.SDK.Application
  fullName: Vasont.Inspire.SDK.Application
  type: Namespace
  assemblies:
  - Vasont.Inspire.SDK
references:
- uid: Vasont.Inspire.SDK.Application.ApplicationExtensions
  commentId: T:Vasont.Inspire.SDK.Application.ApplicationExtensions
  parent: Vasont.Inspire.SDK.Application
  name: ApplicationExtensions
  nameWithType: ApplicationExtensions
  fullName: Vasont.Inspire.SDK.Application.ApplicationExtensions
- uid: Vasont.Inspire.SDK.Application
  commentId: N:Vasont.Inspire.SDK.Application
  name: Vasont.Inspire.SDK.Application
  nameWithType: Vasont.Inspire.SDK.Application
  fullName: Vasont.Inspire.SDK.Application
